[project]
name="scmgr"
version="1.1.1"
authors=[
    { name = "Alex M" }
]
description="Command-line tool for managing and running installations of Star Citizen on Linux."
readme="README.md"
license="GPL-3.0-or-later"
license-files = ["LICENSE"]

dependencies = [
    "PyYAML>=6.0",
    "tomlkit>=0.15",
    "invoke>=3.0"
]
requires-python=">=3.14"

[project.scripts]
scmgr = "scmgr:main"